apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: testapp-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: test@test.com
    privateKeySecretRef:
      name: argocd-tls
    solvers:
    - http01:
        ingress:
          class: azure/application-gateway